// CLIENT ROLE CONFIG (Mirrors Server)
export const ROLE_IDS = {
    MASTER: 1,
    DIRECTOR: 10,
    FRANCHISEE: 20,
    MANAGER: 30,
    LEADER_SALES: 40,
    LEADER_PEDAGOGICAL: 50,
    ADMIN_FINANCIAL: 60,

    // Sub-levels (Implicit)
    CONSULTANT: 41,
    INSTRUCTOR: 51,
    SECRETARY: 52
};

// Groups for UI Logic
export const ROLE_GROUPS = {
    GLOBAL: [ROLE_IDS.MASTER, ROLE_IDS.DIRECTOR], // See All
    ADMIN: [ROLE_IDS.MASTER, ROLE_IDS.DIRECTOR, ROLE_IDS.FRANCHISEE, ROLE_IDS.MANAGER, ROLE_IDS.ADMIN_FINANCIAL], // Admin Dashboard
    COMMERCIAL: [ROLE_IDS.LEADER_SALES, ROLE_IDS.CONSULTANT, ROLE_IDS.FRANCHISEE, ROLE_IDS.MANAGER],
    PEDAGOGICAL: [ROLE_IDS.LEADER_PEDAGOGICAL, ROLE_IDS.INSTRUCTOR, ROLE_IDS.SECRETARY, ROLE_IDS.FRANCHISEE, ROLE_IDS.MANAGER]
};
