// ROLE ID CONSTANTS (Mirrors Backend)
export const ROLE_IDS = {
    // 1-9: Global/High Level
    MASTER: 1,
    DIRECTOR: 2,
    ADMIN: 3,

    // 10-19: Management
    FRANCHISEE: 10,
    MANAGER: 11,

    // 20-29: Operational
    CONSULTANT: 20,
    LEADER_SALES: 21,

    // 30-39: Pedagogical
    PEDAGOGICAL: 30,
    LEADER_PEDAGOGICAL: 31,
    INSTRUCTOR: 32,
    SECRETARY: 33
};

// Groups for Easy Checking
export const ROLE_GROUPS = {
    ADMIN: [ROLE_IDS.MASTER, ROLE_IDS.DIRECTOR, ROLE_IDS.ADMIN, ROLE_IDS.FRANCHISEE, ROLE_IDS.MANAGER],
    GLOBAL: [ROLE_IDS.MASTER, ROLE_IDS.DIRECTOR, ROLE_IDS.ADMIN],
    COMMERCIAL: [ROLE_IDS.LEADER_SALES, ROLE_IDS.CONSULTANT, ROLE_IDS.MANAGER, ROLE_IDS.FRANCHISEE], // Often Franchisee acts as commercial too? Or strictly view?
    PEDAGOGICAL: [ROLE_IDS.LEADER_PEDAGOGICAL, ROLE_IDS.PEDAGOGICAL, ROLE_IDS.INSTRUCTOR, ROLE_IDS.SECRETARY, ROLE_IDS.FRANCHISEE, ROLE_IDS.MANAGER]
};
